### ISSUE TITLE
It's unclear how to use this GitHub Action

### ISSUE THREAD

**Issue by CurtT-OCC** [digicert/ssm-code-signing#15]
Neither the ReadMe content or the provided help link show an example of how to use this action.

What are the inputs? What does it do?

The examples provided in the link do not utilize `digicert/ssm-code-signing` at all!

**Comment by CurtT-OCC** [comment]
To any others that find this, I ended up finding the yaml for a 3rd party action that utilizes this action, and that served well as a primer for this.  If you're so inclined, you can just use the 3rd party action as well.

https://github.com/cognitedata/code-sign-action/blob/main/action.yaml

Here's the meat:
```
- name: Configure Digicert Secure Software Manager
      uses: digicert/ssm-code-signing@v0.0.2
      env:
        SM_API_KEY: ${{ env.SM_API_KEY }}
        SM_CLIENT_CERT_PASSWORD: ${{ env.SM_CLIENT_CERT_PASSWORD }}
        SM_CLIENT_CERT_FILE: ${{ env.SM_CLIENT_CERT_FILE }}
```

This sets up the dependencies and command line utilities you need. You still need to securely provide the cert file and actually sign the file(s) you need.
